# rename this file to config.yaml before start
# qqbot帐号
account:  2769546520
password: "123"

# 验证码图片
port: 3100
host: localhost


# 消息处理，忽略20分钟外的离线消息
# offline_msg_keeptime: 1200

# 插件列表
plugins:
    - help
    - debug
    - apiserver

# apiserver 插件配置
api_port:  3000
api_token: ''